import { MockProduct } from "./mock-product"
export const Products: MockProduct[] = [
    {
        productId: 1,
        name: "The Elder Scrolls V: Skyrim",
        genre: "RPG",
        price: 39.99,
        rating: "Mature",
        endpoint: "https://rawg.io/api/games/the-elder-scrolls-v-skyrim?key=87ad23cdc737468884eb0216a7ba8df9",
        platform: "PC",
        imageUrl: "https://i.imgur.com/waAqQOl.jpg",
    },
    {
        productId: 2,
        name: "Terraria",
        genre: "Platformer",
        price: 9.99,
        rating: "Teen",
        endpoint: "https://rawg.io/api/games/terraria?key=87ad23cdc737468884eb0216a7ba8df9",
        platform: "Xbox One",
        imageUrl: "https://m.media-amazon.com/images/M/MV5BYWU2YmJhZTktNTcxYy00ZmYwLTg2MmQtM2Q5MTZmZjRiNjRkXkEyXkFqcGdeQXVyNzg3NjQyOQ@@._V1_.jpg",
    },
    {
        productId: 3,
        name: "Diablo II",
        genre: "RPG",
        price: 39.99,
        rating: "Mature",
        endpoint: "https://rawg.io/api/games/diablo-2?key=87ad23cdc737468884eb0216a7ba8df9",
        platform: "PC",
        imageUrl: "https://upload.wikimedia.org/wikipedia/ru/0/0e/Bliz_diablo2_lg.jpg",
    },
    {
        productId: 4,
        name: "Borderlands 2",
        genre: "Shooter",
        price: 19.99,
        rating: "Mature",
        endpoint: "https://rawg.io/api/games/borderlands-2?key=87ad23cdc737468884eb0216a7ba8df9",
        platform: "PlayStation 4",
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/5/51/Borderlands_2_cover_art.png/220px-Borderlands_2_cover_art.png",
    },
    {
        productId: 5,
        name: "The Legend of Zelda: Breath of the Wild",
        genre: "RPG",
        price: 59.99,
        rating: "E10+",
        endpoint: "https://rawg.io/api/games/the-legend-of-zelda-breath-of-the-wild?key=87ad23cdc737468884eb0216a7ba8df9",
        platform: "Nintendo Switch",
        imageUrl: "https://www.nintendo.com//content/dam/noa/en_US/games/switch/t/the-legend-of-zelda-breath-of-the-wild-switch/the-legend-of-zelda-breath-of-the-wild-switch-hero.jpg",
    },
]
